-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 01:32:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin` DEFAULT CHARACTER SET utf8 ;
USE `admin` ;

-- -----------------------------------------------------
-- Table `admin`.`Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`Personnel` (
  `idPerso` INT NOT NULL AUTO_INCREMENT,
  `nomPerso` VARCHAR(45) NOT NULL,
  `PrenomPerso` VARCHAR(45) NOT NULL,
  `emailPerso` VARCHAR(45) NOT NULL,
  `sexePerso` VARCHAR(45) NOT NULL,
  `telPerso` VARCHAR(45) NOT NULL,
  `positionPerso` VARCHAR(45) NOT NULL,
  `diplomePerso` VARCHAR(45) NOT NULL,
  `createAtPerso` TIMESTAMP(4) NOT NULL,
  PRIMARY KEY (`idPerso`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPerso_UNIQUE` ON `admin`.`Personnel` (`idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`recruitments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`recruitments` (
  `idrecruit` INT NOT NULL AUTO_INCREMENT,
  `positionRecruit` VARCHAR(45) NOT NULL,
  `salaireRecruit` INT NOT NULL,
  `typeContratRecruit` VARCHAR(45) NOT NULL,
  `dateDebutRecruit` DATE NOT NULL,
  `dateFinRecruit` DATE NOT NULL,
  `createAtRecruit` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idrecruit`),
  CONSTRAINT `fk_recruitments_Personnel`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idrecruit_UNIQUE` ON `admin`.`recruitments` (`idrecruit` ASC);

CREATE INDEX `fk_recruitments_Personnel_idx` ON `admin`.`recruitments` (`Personnel_idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`workRecords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`workRecords` (
  `idWR` INT NOT NULL AUTO_INCREMENT,
  `workDateWR` DATE NOT NULL,
  `hoursWorkedWR` DECIMAL(5,2) NOT NULL,
  `taskDescriptionWR` LONGTEXT NOT NULL,
  `createAtWK` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idWR`),
  CONSTRAINT `fk_workRecords_Personnel1`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idWR_UNIQUE` ON `admin`.`workRecords` (`idWR` ASC);

CREATE INDEX `fk_workRecords_Personnel1_idx` ON `admin`.`workRecords` (`Personnel_idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`performance` (
  `idPerf` INT NOT NULL AUTO_INCREMENT,
  `evaluationDatePerf` DATE NOT NULL,
  `evaluationScorePerf` INT NOT NULL,
  `evaluationRemarksPerf` LONGTEXT NOT NULL,
  `createAtPerf` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idPerf`),
  CONSTRAINT `fk_performance_Personnel1`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPerf_UNIQUE` ON `admin`.`performance` (`idPerf` ASC);

CREATE INDEX `fk_performance_Personnel1_idx` ON `admin`.`performance` (`Personnel_idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`payments` (
  `idPay` INT NOT NULL AUTO_INCREMENT,
  `paymentDatePay` DATE NOT NULL,
  `amountPay` DECIMAL(2) NOT NULL,
  `paymentMethodePay` VARCHAR(45) NOT NULL,
  `createAtPay` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idPay`),
  CONSTRAINT `fk_payments_Personnel1`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPay_UNIQUE` ON `admin`.`payments` (`idPay` ASC);

CREATE INDEX `fk_payments_Personnel1_idx` ON `admin`.`payments` (`Personnel_idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`leaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`leaves` (
  `idLeaves` INT NOT NULL AUTO_INCREMENT,
  `leavesStartDate` DATE NOT NULL,
  `leavesEndDate` DATE NOT NULL,
  `leavesType` VARCHAR(45) NOT NULL,
  `createAtLeaves` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idLeaves`),
  CONSTRAINT `fk_leaves_Personnel1`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idLeaves_UNIQUE` ON `admin`.`leaves` (`idLeaves` ASC);

CREATE INDEX `fk_leaves_Personnel1_idx` ON `admin`.`leaves` (`Personnel_idPerso` ASC);


-- -----------------------------------------------------
-- Table `admin`.`careers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin`.`careers` (
  `idCareers` INT NOT NULL AUTO_INCREMENT,
  `promotiondateCareers` DATE NOT NULL,
  `departmentCareers` VARCHAR(45) NOT NULL,
  `jobTitleCareers` VARCHAR(45) NOT NULL,
  `createAtCareers` TIMESTAMP(4) NOT NULL,
  `Personnel_idPerso` INT NOT NULL,
  PRIMARY KEY (`idCareers`),
  CONSTRAINT `fk_careers_Personnel1`
    FOREIGN KEY (`Personnel_idPerso`)
    REFERENCES `admin`.`Personnel` (`idPerso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCareers_UNIQUE` ON `admin`.`careers` (`idCareers` ASC);

CREATE INDEX `fk_careers_Personnel1_idx` ON `admin`.`careers` (`Personnel_idPerso` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
